# Generated by Django 2.1.4 on 2019-01-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_key',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
