# Generated by Django 2.1.4 on 2019-01-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='q_key',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
